[package]
name = "bevy_gltf_animation"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16", default-features = false, features = [
    "bevy_animation",
] }

[dev-dependencies]
bevy = "0.16"

[lints.clippy]
type-complexity = "allow"
too-many-arguments = "allow"
